[general]
static=yes
writeprotect=no

[internal]
; Appeler le SVI
exten => 1000,1,Goto(mon-svi,s,1)

; Appeler le poste physique (CHANGEMENT : PJSIP au lieu de SIP)
exten => 1001,1,Dial(PJSIP/compte-phone,20)
exten => 1001,n,Hangup()

[mon-svi]
exten => s,1,Answer()
; On retire la ligne LANGUAGE qui pose erreur
exten => s,n,Background(demo-congrats)   ; Son par défaut qui existe sûr
exten => s,n,WaitExten(10)

exten => 1,1,Goto(menu-compte,s,1)
exten => 2,1,Goto(menu-rh,s,1)
exten => 3,1,Goto(menu-support,s,1)

exten => i,1,Playback(pbx-invalid)
exten => i,n,Goto(s,1)

[menu-compte]
exten => s,1,Answer()
exten => s,n,Background(digits/1)   ; Son par défaut simple ("Un")
exten => s,n,WaitExten(5)

; Redirection (CHANGEMENT : PJSIP au lieu de SIP)
exten => 1,1,NoOp(Appel Service Facture)
exten => 1,n,Dial(PJSIP/compte-phone,10) 
exten => 1,n,GotoIf($["${DIALSTATUS}" = "ANSWER"]?fin) 
exten => 1,n,VoiceMail(1001@default,u)   
exten => 1,n(fin),Hangup()

; -- Choix 2 : Redirection vers le 1002 --
exten => 2,1,Dial(PJSIP/1002,10)           ; Sonne 10 secondes sur le poste 1002
exten => 2,n,GotoIf($["${DIALSTATUS}" = "ANSWER"]?fin) ; Si ça répond, on raccroche
exten => 2,n,VoiceMail(1002@default,u)     ; Sinon, on tombe sur le répondeur du 1002
exten => 2,n(fin),Hangup()


[menu-rh]
exten => s,1,Answer()
exten => s,n,Playback(demo-congrats)
exten => s,n,Hangup()

[menu-support]
exten => s,1,Answer()
exten => s,n,Playback(please-hold)
exten => s,n,Hangup()
