[general]
static=yes
writeprotect=no

[internal]
; --- SVI ---
exten => 1000,1,Goto(mon-svi,s,1)

; --- Poste 1001 (CORRIGÉ : on appelle PJSIP/1001 et plus compte-phone) ---
exten => 1001,1,Dial(PJSIP/1001,20)
exten => 1001,n,Hangup()

; --- Poste 1002 (AJOUTÉ) ---
exten => 1002,1,Dial(PJSIP/1002,20)
exten => 1002,n,Hangup()

[mon-svi]
exten => s,1,Answer()
exten => s,n,Background(demo-congrats)
exten => s,n,WaitExten(10)

exten => 1,1,Goto(menu-compte,s,1)
exten => 2,1,Goto(menu-rh,s,1)
exten => 3,1,Goto(menu-support,s,1)

exten => i,1,Playback(pbx-invalid)
exten => i,n,Goto(s,1)

[menu-compte]
exten => s,1,Answer()
exten => s,n,Background(digits/1)
exten => s,n,WaitExten(5)

; CORRIGÉ ICI AUSSI : on appelle PJSIP/1001
exten => 1,1,NoOp(Appel Service Facture)
exten => 1,n,Dial(PJSIP/1001,10)
exten => 1,n,GotoIf($["${DIALSTATUS}" = "ANSWER"]?fin)
exten => 1,n,VoiceMail(1001@default,u)
exten => 1,n(fin),Hangup()

; Choix 2 : Redirection vers le 1002
exten => 2,1,Dial(PJSIP/1002,10)
exten => 2,n,GotoIf($["${DIALSTATUS}" = "ANSWER"]?fin)
exten => 2,n,VoiceMail(1002@default,u)
exten => 2,n(fin),Hangup()

[menu-rh]
exten => s,1,Answer()
exten => s,n,Playback(demo-congrats)
exten => s,n,Hangup()

[menu-support]
exten => s,1,Answer()
exten => s,n,Playback(please-hold)
exten => s,n,Hangup()
