[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:4970

[1001]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=auth1001
aors=1001
direct_media=yes
rtp_symmetric=yes
rewrite_contact=yes


[auth1001]
type=auth
auth_type=userpass
password=1234
username=1001

[1001]
type=aor
max_contacts=5

[1002]
    type=endpoint
    context=internal
    disallow=all
    allow=ulaw
    auth=auth1002
    aors=1002
    direct_media=yes
    rtp_symmetric=yes
    rewrite_contact=yes

[auth1002]
    type=auth
    auth_type=userpass
    password=4321
    username=1002

[1002]
    type=aor
    max_contacts=5


[compte-phone]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=compte-phone-auth
aors=compte-phone

[compte-phone]
type=aor
max_contacts=1

[compte-phone-auth]
type=auth
auth_type=userpass
username=compte-phone
password=password123
